In [7]:
import numpy as np 

In [8]:
arr = np.array([1,3,4,5,6,7,8])

In [9]:
arr

array([1, 3, 4, 5, 6, 7, 8])

In [10]:
arr2 = np.array([9,8,7,6,9,0,8,6])

In [11]:
arr2

array([9, 8, 7, 6, 9, 0, 8, 6])

-----

In [12]:
np.concatenate((arr,arr2)) # raw 

array([1, 3, 4, 5, 6, 7, 8, 9, 8, 7, 6, 9, 0, 8, 6])

In [13]:
np.delete(arr,2) # delete index of number 2

array([1, 3, 5, 6, 7, 8])

In [16]:
arr = np.arange(9)
arr1 = arr.reshape(3,3)

In [19]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
np.delete(arr1,1,axis=0) # raw 

array([[0, 1, 2],
       [6, 7, 8]])

In [21]:
np.delete(arr1,1,axis=1)  #Column 

array([[0, 2],
       [3, 5],
       [6, 8]])

In [22]:
arr1.sum()

36

In [23]:
arr1.sum(axis=0)

array([ 9, 12, 15])

In [24]:
arr1.sum(axis=1)

array([ 3, 12, 21])

In [25]:
arr1.min()

0

In [26]:
arr1.max()

8